AWSTemplateFormatVersion: '2010-09-09'
Description: Once per account
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Account name
        Parameters:
          - AccountName
      - Label:
          default: User name
        Parameters:
          - UserName1
      - Label:
          default: Password should have at least one uppercase letter and number and symbol. (20 characters or more)
        Parameters:
          - UserPassword1

Parameters:
  AccountName:
    Type: String
    Description: For example quail, kyt, tsumagari
  UserName1:
    Type: String
    Description: For example ikeda
  UserPassword1:
    Type: String
    NoEcho: true

Resources:
  User1:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref UserPassword1
        PasswordResetRequired: False
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/PowerUserAccess
        - !Ref ConsoleUserPolicy
      UserName: !Sub ${UserName1}@${AccountName}

  ConsoleUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ConsoleUserPolicy-${UserName1}
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource:
              - '*'
            Action:
              - ecs:UpdateService
              - secretsmanager:DescribeSecret
              - secretsmanager:PutSecretValue
              - secretsmanager:CreateSecret
              - secretsmanager:DeleteSecret
              - secretsmanager:CancelRotateSecret
              - iam:AttachRolePolicy
              - iam:ListVirtualMFADevices
              - secretsmanager:ListSecretVersionIds
              - secretsmanager:UpdateSecret
              - iam:CreatePolicy
              - secretsmanager:GetRandomPassword
              - secretsmanager:GetResourcePolicy
              - iam:PassRole
              - secretsmanager:GetSecretValue
              - secretsmanager:RestoreSecret
              - secretsmanager:RotateSecret
              - secretsmanager:UpdateSecretVersionStage
          - Effect: Allow
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:mfa/${!aws:username}
            Action:
              - iam:DeleteVirtualMFADevice
              - iam:CreateVirtualMFADevice
          - Effect: Allow
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:user/${!aws:username}
            Action:
              - iam:DeactivateMFADevice
              - iam:EnableMFADevice
              - iam:ResyncMFADevice
              - iam:ListMFADevices
Outputs:
  LoginURL:
    Description: LoginURL
    Value: !Sub https://${AWS::AccountId}.signin.aws.amazon.com/console
