AWSTemplateFormatVersion: '2010-09-09'
Description: Once per account
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCidr
          - PublicSubnetACidr
          - PublicSubnetCCidr
          - PublicSubnetDCidr
          - PrivateSubnetACidr
          - PrivateSubnetCCidr
          - PrivateSubnetDCidr

Parameters:
  VPCCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetACidr:
    Type: String
    Default: 10.0.0.0/24
  PublicSubnetCCidr:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnetDCidr:
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnetACidr:
    Type: String
    Default: 10.0.3.0/24
  PrivateSubnetCCidr:
    Type: String
    Default: 10.0.4.0/24
  PrivateSubnetDCidr:
    Type: String
    Default: 10.0.5.0/24
  AZa:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  AZc:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1c
  AZd:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1d

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZa
      CidrBlock: !Ref PublicSubnetACidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: public-subnet-a
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZc
      CidrBlock: !Ref PublicSubnetCCidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: public-subnet-c

  PublicSubnetD:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZd
      CidrBlock: !Ref PublicSubnetDCidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: public-subnet-d

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZa
      CidrBlock: !Ref PrivateSubnetACidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: private-subnet-a

  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZc
      CidrBlock: !Ref PrivateSubnetCCidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: private-subnet-c

  PrivateSubnetD:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZd
      CidrBlock: !Ref PrivateSubnetDCidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: private-subnet-d

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: public-route

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: private-route

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetDRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetD
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetDRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetD
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  VPC:
    Value: !Ref VPC
    Export:
      Name: vpc

  PublicSubnetA:
    Value: !Ref PublicSubnetA
    Export:
      Name: public-subnet-a

  PublicSubnetC:
    Value: !Ref PublicSubnetC
    Export:
      Name: public-subnet-c

  PublicSubnetD:
    Value: !Ref PublicSubnetD
    Export:
      Name: public-subnet-d

  PrivateSubnetA:
    Value: !Ref PrivateSubnetA
    Export:
      Name: private-subnet-a

  PrivateSubnetC:
    Value: !Ref PrivateSubnetC
    Export:
      Name: private-subnet-c

  PrivateSubnetD:
    Value: !Ref PrivateSubnetD
    Export:
      Name: private-subnet-d
