AWSTemplateFormatVersion: '2010-09-09'
Description: Once per account
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Docker Configurations
        Parameters:
          - SecretsName
          - DockerUser
          - DockerToken

Parameters:
  SecretsName:
    Type: String
    Default: docker_token_for_codebuild
  DockerUser:
    Type: String
    Default: quail9816
    Description: Docker Login User Name
  DockerToken:
    Description: Docker Access Token
    Type: String
    NoEcho: true

Resources:
  SecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretsName
      SecretString: !Sub '{"DOCKER_USER":"${DockerUser}","DOCKER_TOKEN":"${DockerToken}"}'

Outputs:
  SourceConnection:
    Value: !Ref SecretsManager
    Export:
      Name: SecretsManagerARN-Of-DockerToken
